urxvt:
  rules:
    - class_group: URxvt
    - match: exact
      field: class_group
      val: URxvt
    - match: regex
      field: class_group
      val: ^URxv[td]
    - match: substring
      field: class_group
      val: Rxv
  actions:
    - name: workspace
      arg: 1
    - maximize: true
    - activate_workspace: 1
